@Library('sharedlibrary@main') _  // Load the shared library
 environment { 
     testScript = load 'CI/vars/test.groovy'
            }
pipeline {
    agent any
    
    stages {
        stage('Execute Pipeline Steps') {
            steps {
                script{
                    test.cleanWorkspace()
                    test.cloneRepository()
                }
            }
        }
    }
}
